name: Deploy to AWS EC2 (NGINX)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: if your index.html is in a subfolder, adjust the path below
      - name: Copy index.html to EC2 instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'index.html'
          target: '/tmp/index.html'

      - name: Deploy on EC2 and restart NGINX
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mv /tmp/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html || true
            sudo systemctl restart nginx
            echo "Deployment successful!"
